# Myntra Sales Data Cleaning & Preparation

This notebook focuses on cleaning and preparing Myntra sales data for analysis and visualization.

## Key Steps:
- Data cleaning
- Data validation
- Feature engineering

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
from datetime import date

In [3]:
uploaded = files.upload()

Saving Myntra Sales Analysis.csv to Myntra Sales Analysis.csv

In [4]:
df = pd.read_csv("Myntra Sales Analysis.csv")
df.head()

/tmp/ipykernel_6923/4078503449.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Myntra Sales Analysis.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Myntra.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,4/30/2022,Shipped,Myntra,Myntra.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,4/30/2022,Cancelled,Merchant,Myntra.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,4/30/2022,Shipped,Myntra,Myntra.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [5]:
df.columns[23]

'Unnamed: 22'

In [6]:
df.iloc[:, 23].unique()

array([nan, False], dtype=object)

In [7]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed', case = False)]
df = df.drop(columns = ['index'])

Removed unnecessary columns generated during CSV import (e.g., 'Unnamed' columns) to clean the dataset.

In [8]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Myntra.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
1,171-9198151-1101146,4/30/2022,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,4/30/2022,Shipped,Myntra,Myntra.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
3,403-9615377-8133951,4/30/2022,Cancelled,Merchant,Myntra.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
4,407-1069790-7240320,4/30/2022,Shipped,Myntra,Myntra.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN

In [9]:
df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('-', '_')

In [10]:
df['date'] = pd.to_datetime(df['date'], errors = 'coerce')

In [11]:
df['ship_postal_code'] = df['ship_postal_code'].astype('Int64')
df['courier_status'] = df['courier_status'].fillna('Unkown')

In [12]:
df.isnull().sum()

order_id                  0
date                  55109
status                    0
fulfilment                0
sales_channel_            0
ship_service_level        0
style                     0
sku                       0
category                  0
size                      0
asin                      0
courier_status            0
qty                       0
currency               7795
amount                 7795
ship_city                33
ship_state               33
ship_postal_code         33
ship_country             33
promotion_ids         49153
b2b                       0
fulfilled_by          89698
dtype: int64

In [13]:
df = df[df['amount'].notnull()].copy()

In [14]:
df['currency'] = df['currency'].fillna('INR')

In [15]:
df['promotion_ids'] = df['promotion_ids'].fillna('No Promotion')
df['fulfilled_by'] = df['fulfilled_by'].fillna('Unknown')

In [16]:
df['revenue'] = df['qty'] * df['amount']

In [17]:
df['month'] = df['date'].dt.month

Handled SettingWithCopyWarning by creating an explicit copy of the filtered DataFrame to ensure safe modifications.

In [18]:
df.describe()

,date,qty,amount,ship_postal_code,revenue,month
count,69420,121180.000000,121180.000000,121149.0,121180.000000,69420.000000
mean,2022-05-17 10:22:42.834917888,0.961231,648.561465,463652.687525,627.450124,4.859752
min,2022-03-31 00:00:00,0.000000,0.000000,110001.0,0.000000,3.000000
25%,2022-04-23 00:00:00,1.000000,449.000000,382421.0,432.000000,4.000000
50%,2022-05-18 00:00:00,1.000000,605.000000,500032.0,597.000000,5.000000
75%,2022-06-14 00:00:00,1.000000,788.000000,600021.0,777.000000,6.000000
max,2022-06-29 00:00:00,8.000000,5584.000000,989898.0,44672.000000,6.000000
std,NaN,0.214354,281.211687,191316.128616,368.010104,0.817283

## Data Cleaning Steps

- Removed unnecessary columns ('index', unnamed columns)
- Standardized column names
- Converted date column to datetime format
- Handled missing values in key columns
- Created new features (revenue, month)

In [19]:
df = df[df['qty'] > 0]

In [20]:
df = df[df['amount'] > 0]

In [21]:
df = df[df['revenue'] < 10000]

In [22]:
df = df[df['ship_postal_code'].notnull()]

In [23]:
df.describe()

,date,qty,amount,ship_postal_code,revenue,month
count,64892,113666.000000,113666.000000,113666.0,113666.000000,64892.000000
mean,2022-05-17 13:11:04.611970560,1.003616,662.998302,463893.524466,667.644054,4.862479
min,2022-03-31 00:00:00,1.000000,199.000000,110001.0,199.000000,3.000000
25%,2022-04-23 00:00:00,1.000000,459.000000,382480.0,459.000000,4.000000
50%,2022-05-18 00:00:00,1.000000,625.000000,500033.0,625.000000,5.000000
75%,2022-06-14 00:00:00,1.000000,788.000000,600019.0,788.000000,6.000000
max,2022-06-29 00:00:00,4.000000,2894.000000,855117.0,8272.000000,6.000000
std,NaN,0.066026,268.428226,190893.847471,297.419023,0.817818

## Data Quality Observations

- Removed records with zero quantity and zero amount
- Identified and filtered extreme revenue outliers
- Handled missing postal codes
- Observed that most orders consist of single items
- Dataset spans from March to June 2022

In [24]:
df[df['revenue'] > 5000]

,order_id,date,status,fulfilment,sales_channel_,ship_service_level,style,sku,category,size,...,amount,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by,revenue,month
3289,406-3338330-9401954,2022-04-28,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,JNE3798,JNE3798-KR-M,Western Dress,M,...,2175.0,KANPUR,UTTAR PRADESH,208001,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,6525.0,4.0
17338,403-2332292-9207530,2022-04-20,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,JNE2265,JNE2265-KR-501-XXL,kurta,XXL,...,1316.0,NEW DELHI,DELHI,110063,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,5264.0,4.0
20534,406-1124784-1093950,2022-04-18,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,J0341,J0341-DR-M,Western Dress,M,...,2232.0,Kochi,KERALA,682036,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,6696.0,4.0
28814,408-9885439-6698733,2022-04-13,Shipped,Myntra,Myntra.in,Expedited,J0285,J0285-SKD-S,Set,S,...,2864.0,BENGALURU,KARNATAKA,560032,IN,No Promotion,False,Unknown,5728.0,4.0
32278,171-7532609-3249907,NaT,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,JNE3797,JNE3797-KR-M,Western Dress,M,...,2175.0,RAXAUL BAZAR,BIHAR,845305,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,6525.0,NaN
33333,405-4755854-9568304,NaT,Shipped,Myntra,Myntra.in,Expedited,JNE3465,JNE3465-KR-S,kurta,S,...,2068.0,MANGALURU,KARNATAKA,575006,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,8272.0,NaN
34572,404-0430156-5953153,NaT,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,SET249,SET249-KR-NP-XL,Set,XL,...,2040.0,MUMBAI,MAHARASHTRA,400069,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,6120.0,NaN
38113,407-8127937-6618709,NaT,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,SET186,SET186-KR-DH-S,Set,S,...,1893.0,PUNE,MAHARASHTRA,411037,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,5679.0,NaN
46555,402-7068488-0986720,NaT,Shipped,Myntra,Myntra.in,Expedited,SET098,SET098-KR-PP-M,Set,M,...,2016.0,ARSIKERE,KARNATAKA,573103,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,6048.0,NaN
46867,408-9783812-8938718,NaT,Shipped,Myntra,Myntra.in,Expedited,SET269,SET269-KR-NP-XL,Set,XL,...,2397.0,NAMAKKAL,TAMIL NADU,637001,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,7191.0,NaN
49348,408-3889919-3918768,2022-05-31,Shipped,Myntra,Myntra.in,Expedited,SET331,SET331-KR-NP-XS,Set,XS,...,1923.0,Thiruchengode,TAMIL NADU,637215,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,5769.0,5.0
54605,171-9419863-7830701,2022-05-27,Shipped,Myntra,Myntra.in,Expedited,J0341,J0341-DR-XXL,Western Dress,XXL,...,2655.0,NAVI MUMBAI,MAHARASHTRA,410206,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,7965.0,5.0
57091,405-3036482-4663513,2022-05-25,Shipped,Myntra,Myntra.in,Expedited,J0119,J0119-TP-XXL,Top,XXL,...,1722.0,DOMBIVLI,MAHARASHTRA,421201,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,5166.0,5.0
63974,408-9361250-7029128,2022-05-19,Shipped,Myntra,Myntra.in,Expedited,J0230,J0230-SKD-XL,Set,XL,...,2698.0,KOLKATA,WEST BENGAL,700016,IN,No Promotion,True,Unknown,5396.0,5.0
74960,171-3502000-6477118,NaT,Shipped,Myntra,Myntra.in,Expedited,SAR135,SAR135,Saree,Free,...,2058.0,VILLUPURAM,TAMIL NADU,605602,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,6174.0,NaN
75760,402-9141667-1791537,NaT,Cancelled,Myntra,Myntra.in,Expedited,SET364,SET364-KR-NP-XXL,Set,XXL,...,2676.0,CHENNAI,TAMIL NADU,600053,IN,No Promotion,False,Unknown,5352.0,NaN
76157,171-1831905-5247524,NaT,Shipped,Myntra,Myntra.in,Expedited,SET044,SET044-KR-NP-S,Set,S,...,1836.0,GUNTAKAL,ANDHRA PRADESH,515801,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,5508.0,NaN
79902,405-4225331-3338755,NaT,Shipped - Returned to Seller,Merchant,Myntra.in,Standard,JNE3671,JNE3671-TU-M,Top,M,...,1764.0,MAHENDRAGARH,HARYANA,123029,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,5292.0,NaN
79903,405-4225331-3338755,NaT,Shipped - Returned to Seller,Merchant,Myntra.in,Standard,JNE3673,JNE3673-TU-M,Top,M,...,1797.0,MAHENDRAGARH,HARYANA,123029,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,5391.0,NaN
113339,403-1620002-1689968,NaT,Shipped - Delivered to Buyer,Merchant,Myntra.in,Standard,JNE3405,JNE3405-KR-L,kurta,L,...,1740.0,ALIGARH,UTTAR PRADESH,202001,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,6960.0,NaN
120770,402-7744718-3391556,NaT,Shipped - Returned to Seller,Merchant,Myntra.in,Standard,JNE3609,JNE3609-KR-L,kurta,L,...,1704.0,Chennai,TAMIL NADU,600033,IN,Myntra PLCC Free-Financing Universal Merchant ...,False,Easy Ship,5112.0,NaN
121225,404-4712917-7300332,NaT,Shipped,Myntra,Myntra.in,Expedited,SET278,SET278-KR-NP-XXXL,Set,3XL,...,2894.0,MUMBAI,MAHARASHTRA,400081,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,5788.0,NaN
124576,406-9485910-0797142,NaT,Shipped,Myntra,Myntra.in,Expedited,JNE2305,JNE2305-KR-533-M,kurta,M,...,1504.0,CHENNAI,TAMIL NADU,600122,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,Unknown,6016.0,NaN

## Post-Cleaning Observations

- Removed invalid records (zero quantity and amount)
- Data distribution is now consistent and realistic
- Majority of transactions involve single-item purchases
- Revenue closely follows product price due to low quantity variation
- Dataset spans March to June 2022

In [25]:
for col in df.columns:
  print(col)

order_id
date
status
fulfilment
sales_channel_
ship_service_level
style
sku
category
size
asin
courier_status
qty
currency
amount
ship_city
ship_state
ship_postal_code
ship_country
promotion_ids
b2b
fulfilled_by
revenue
month

In [26]:
df.rename(columns={
    'sales_channel_' : 'sales_channel'
}, inplace = True)

In [27]:
for col in df.columns:
  print(col)

order_id
date
status
fulfilment
sales_channel
ship_service_level
style
sku
category
size
asin
courier_status
qty
currency
amount
ship_city
ship_state
ship_postal_code
ship_country
promotion_ids
b2b
fulfilled_by
revenue
month

In [28]:
df.to_csv("cleaned_myntra_sales_data.csv", index = False)

In [ ]:
files.download("cleaned_myntra_sales_data.csv")

In [29]:
len(df.columns)

24

In [30]:
df['amount'] = pd.to_numeric(df['amount'], errors = 'coerce')

In [31]:
df['b2b'] = df['b2b'].astype(str).str.lower().map({'true': True, 'false': False})

In [32]:
df = df[df['qty'].notnull()]

In [33]:
df.to_csv("cleaned_myntra_data.csv", index = False)

In [ ]:
files.download('cleaned_myntra_data.csv')

In [34]:
for i, col in enumerate(df.columns):
  print(i, col)

0 order_id
1 date
2 status
3 fulfilment
4 sales_channel
5 ship_service_level
6 style
7 sku
8 category
9 size
10 asin
11 courier_status
12 qty
13 currency
14 amount
15 ship_city
16 ship_state
17 ship_postal_code
18 ship_country
19 promotion_ids
20 b2b
21 fulfilled_by
22 revenue
23 month

In [35]:
df = df[[
    'order_id',
    'date',
    'status',
    'fulfilment',
    'sales_channel',
    'ship_service_level',
    'style',
    'sku',
    'category',
    'size',
    'asin',
    'courier_status',
    'qty',
    'currency',
    'amount',
    'ship_city',
    'ship_state',
    'ship_postal_code',
    'ship_country',
    'promotion_ids',
    'fulfilled_by',
    'b2b',
    'revenue',
    'month'
]]

In [36]:
df['b2b'].unique()

array([False,  True])

In [37]:
df['b2b'] = df['b2b'].astype(str).str.lower().map({'true': True, 'false': False})

In [38]:
df.to_csv("myntra.csv", index = False)

In [ ]:
files.download("myntra.csv")

In [39]:
df['month'] = pd.to_numeric(df['month'], errors = 'coerce').fillna(0).astype(int)

In [40]:
df['month'].unique()

array([4, 0, 3, 5, 6])

In [41]:
df.to_csv("Myntra.csv", index = False)

In [42]:
files.download("Myntra.csv")